# Generated by Django 3.1.1 on 2020-09-26 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('item_type', models.CharField(max_length=255, verbose_name='Item Type')),
                ('quantity_available', models.IntegerField(default=0, verbose_name='Quantity Available')),
                ('quantity_required', models.IntegerField(default=1, verbose_name='Quantity Required')),
            ],
        ),
        migrations.CreateModel(
            name='Donated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='account.donor')),
                ('donated_on', models.DateTimeField(auto_now_add=True)),
                ('donated_quantity', models.IntegerField(verbose_name='Quantity Donated')),
                ('donated_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationitem')),
            ],
        ),
    ]
