# Generated by Django 3.1.1 on 2020-09-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationitem',
            name='quantity_available',
        ),
    ]
